# Generated by Django 3.2.3 on 2021-05-17 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('teacher', models.CharField(max_length=250)),
                ('room', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='shedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dn', models.CharField(max_length=25)),
                ('date', models.DateField()),
                ('par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ugc.pars')),
            ],
        ),
    ]
