# Generated by Django 3.2.3 on 2021-05-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shedule',
            name='par',
        ),
        migrations.AddField(
            model_name='shedule',
            name='par',
            field=models.ManyToManyField(to='ugc.pars'),
        ),
    ]
