# Generated by Django 3.2.3 on 2021-05-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0002_auto_20210518_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='shedule',
            name='group',
            field=models.CharField(default='default', max_length=25, verbose_name='Группа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pars',
            name='title',
            field=models.CharField(max_length=25, verbose_name='Название пары'),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='dn',
            field=models.CharField(max_length=25, verbose_name='День недели'),
        ),
    ]
